[formatter.haskell]
command = "fourmolu"
options = [
    "--ghc-opt",
    "-XImportQualifiedPost",
    "--ghc-opt",
    "-XTypeApplications",
    "--mode",
    "inplace",
    "--check-idempotence",
]
includes = ["*.hs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.cabal]
command = "cabal-fmt"
options = ["--inplace"]
includes = ["*.cabal"]
